<?php

/**
 * @file
 * Theming helpers for the SolKit Distribution
 */

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function solkit_theme_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_system_info_alter().
 */
function solkit_theme_system_info_alter(&$info, $file, $type) {
  // Hide blacklisted themes.
  $blacklisted_themes = _solkit_theme_get_blacklisted_themes();
  if ($type == 'theme') {
    if (in_array($file->name, $blacklisted_themes)) {
      $info['hidden'] = TRUE;
    }
  }
}

/**
 * Returns an array of themes to blacklist.
 */
function _solkit_theme_get_blacklisted_themes() {
  return array(
    'stark',
    'bartik',
    'responsive_bartik',
    'garland',
    'octal',
    'radix',
    'restaurant_octal',
  );
}